### ISSUE TITLE
default layout doesn't work after install_theme

### ISSUE THREAD

**Issue by dgoldie** [drnic/install_theme#2]
I tried this:
install_theme . ~/code/css_templates/exposure/exposure "#content:text"  -a "main/index" --partial "sidebar:#sidebar:text" --haml
with this template and rails 2.3.5
http://www.freecsstemplates.org/preview/exposure

then created a main controller, but the index page doesn't use the default layout -- application.html.haml? If you specify a layout in the controller, you can get it to work.

...shouldn't it?

also a couple of minor bugs ...
1. there was a "- end" in one of the templates, but I think I've seen that before with html2haml.??
2. had to change the stylesheet link to = stylesheet_link_tag "default"

thanks

**Comment by drnic** [comment]
Regarding the "- end" bug, which version of haml are you using? I know we did a bunch of html2haml changes into the drnic-haml gem; they were then rewritten into the haml src, but not sure if they are released as "haml" or "haml-edge" gem, nor how well they work :/

**Comment by dgoldie** [comment]
good point...I'm at 2.2.13 and I see a 2.2.20
tried to update but am getting this...
doug@zeus ~/code/spikes 
$ gem update haml
Updating installed gems
Updating haml
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SocketError: getaddrinfo: nodename nor servname provided, or not known (http://gemcutter.org/gems/haml-2.2.20.gem)

strange... not seen that before.

**Comment by drnic** [comment]
That's probably a temporary gemcutter issue. Try again.

Last night I upgraded install_theme to 0.8.2 so grab that as well.

Also, throw the following install_theme.yml into your theme folder which has all the defaults that seem to work for me with that theme:

```
--- 
image_dir: images
index_path: index.html
content_path: "#content text()"
no_sass: false
stylesheet_dir: ""
javascript_dir: javascripts
partials: 
  sidebar: "#sidebar ul text()"
  menu: "#menu ul text()"
```
